#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pytest_asyncio
Version  : 0.18.0
Release  : 34
URL      : https://files.pythonhosted.org/packages/72/2b/67cf2070361f4160403210530bab713bacc2024d09f0022f1142a17ff596/pytest-asyncio-0.18.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/72/2b/67cf2070361f4160403210530bab713bacc2024d09f0022f1142a17ff596/pytest-asyncio-0.18.0.tar.gz
Summary  : Pytest support for asyncio
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pytest_asyncio-license = %{version}-%{release}
Requires: pypi-pytest_asyncio-python = %{version}-%{release}
Requires: pypi-pytest_asyncio-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(pytest)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(typing_extensions)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
pytest-asyncio: pytest support for asyncio
==========================================

%package license
Summary: license components for the pypi-pytest_asyncio package.
Group: Default

%description license
license components for the pypi-pytest_asyncio package.


%package python
Summary: python components for the pypi-pytest_asyncio package.
Group: Default
Requires: pypi-pytest_asyncio-python3 = %{version}-%{release}

%description python
python components for the pypi-pytest_asyncio package.


%package python3
Summary: python3 components for the pypi-pytest_asyncio package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_asyncio)
Requires: pypi(pytest)
Requires: pypi(typing_extensions)

%description python3
python3 components for the pypi-pytest_asyncio package.


%prep
%setup -q -n pytest-asyncio-0.18.0
cd %{_builddir}/pytest-asyncio-0.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644250526
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pytest_asyncio
cp %{_builddir}/pytest-asyncio-0.18.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pytest_asyncio/92a74693f02c8e78dd90b2014c52bc35a95bab86
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pytest_asyncio/92a74693f02c8e78dd90b2014c52bc35a95bab86

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
